package io.github.twatanabe1436.hanaso.core

// ロールプレイのシナリオとフリートークのトピック。
// setting / aiRole / userRole / opener は英語 (プロンプト用)、*Ja は画面表示用。

object Catalog {
    val scenarios: List<Scenario> = listOf(
        Scenario(
            id = "cafe",
            category = Category.DAILY,
            emoji = "☕",
            titleJa = "カフェで注文する",
            titleEn = "Ordering at a Café",
            level = Level.BEGINNER,
            descriptionJa = "朝のカフェでドリンクと軽食を注文しましょう。サイズやカスタマイズも伝えてみよう。",
            setting = "A busy but friendly coffee shop in Seattle on a weekday morning.",
            aiName = "Jamie",
            aiRole = "Jamie, a cheerful barista taking orders at the counter.",
            userRole = "A customer ordering a drink and something to eat.",
            userRoleJa = "お客さん",
            opener = "Hi there, good morning! What can I get started for you today?",
            missions = listOf(
                Mission("drink", "ドリンクをサイズ付きで注文する"),
                Mission("custom", "カスタマイズを頼む（ミルク変更・氷少なめなど）"),
                Mission("food", "食べ物をひとつ注文する"),
            ),
            keyPhrases = listOf(
                Phrase("Can I get a medium latte, please?", "ラテのMサイズをください。"),
                Phrase("Could you make it with oat milk?", "オーツミルクに変えてもらえますか？"),
                Phrase("I'll also have a blueberry muffin.", "ブルーベリーマフィンもお願いします。"),
                Phrase("For here, please.", "店内で食べます。"),
            ),
        ),
        Scenario(
            id = "directions",
            category = Category.DAILY,
            emoji = "🗺️",
            titleJa = "道をたずねる",
            titleEn = "Asking for Directions",
            level = Level.BEGINNER,
            descriptionJa = "旅先で美術館への行き方を地元の人に聞きます。聞き取れなかったら聞き返してみよう。",
            setting = "A street corner in downtown Chicago on a sunny afternoon.",
            aiName = "Pat",
            aiRole = "Pat, a friendly local who is walking by and happy to help. The art museum is about a 10-minute walk: two blocks straight, then turn left at the big bookstore; or take bus 6 for two stops.",
            userRole = "A tourist looking for the art museum.",
            userRoleJa = "観光客",
            opener = "Oh, hi! You look a little lost. Can I help you find something?",
            missions = listOf(
                Mission("ask", "美術館への行き方をたずねる"),
                Mission("time", "かかる時間や距離を確認する"),
                Mission("confirm", "聞いた道順を繰り返して確認する"),
            ),
            keyPhrases = listOf(
                Phrase("Excuse me, how do I get to the art museum?", "すみません、美術館へはどう行けばいいですか？"),
                Phrase("How long does it take to walk there?", "歩いてどのくらいかかりますか？"),
                Phrase("So I go straight and turn left at the bookstore, right?", "まっすぐ行って本屋を左ですね？"),
                Phrase("Sorry, could you say that again?", "すみません、もう一度言ってもらえますか？"),
            ),
        ),
        Scenario(
            id = "restaurant",
            category = Category.DAILY,
            emoji = "🍝",
            titleJa = "レストランで食事",
            titleEn = "Dining at a Restaurant",
            level = Level.BEGINNER,
            descriptionJa = "イタリアンレストランで、おすすめを聞いたり注文したり、最後にお会計を頼みます。",
            setting = "A cozy Italian restaurant in London in the evening.",
            aiName = "Marco",
            aiRole = "Marco, a warm and chatty server. Today's specials are seafood risotto and a mushroom pasta; the tiramisu is famous.",
            userRole = "A diner having dinner.",
            userRoleJa = "お客さん",
            opener = "Good evening, welcome! Here are your menus. Can I start you off with something to drink?",
            missions = listOf(
                Mission("recommend", "おすすめを聞く"),
                Mission("order", "メイン料理を注文する"),
                Mission("check", "お会計を頼む"),
            ),
            keyPhrases = listOf(
                Phrase("What do you recommend?", "おすすめは何ですか？"),
                Phrase("I'd like the mushroom pasta, please.", "きのこのパスタをお願いします。"),
                Phrase("Does this have any nuts in it?", "これにナッツは入っていますか？"),
                Phrase("Could we get the check, please?", "お会計をお願いできますか？"),
            ),
        ),
        Scenario(
            id = "immigration",
            category = Category.TRAVEL,
            emoji = "🛂",
            titleJa = "入国審査",
            titleEn = "Passport Control",
            level = Level.BEGINNER,
            descriptionJa = "空港の入国審査で、旅の目的や滞在期間を答えます。落ち着いてはっきり答えよう。",
            setting = "The passport control counter at San Francisco International Airport.",
            aiName = "Officer Reed",
            aiRole = "Officer Reed, a calm and professional immigration officer. Ask typical questions one at a time: purpose of visit, length of stay, where they will stay, occupation, return ticket.",
            userRole = "A traveler arriving from Japan.",
            userRoleJa = "旅行者",
            opener = "Hello. Passport, please. What's the purpose of your visit?",
            missions = listOf(
                Mission("purpose", "渡航目的を答える"),
                Mission("stay", "滞在期間と滞在先を答える"),
                Mission("job", "職業を答える"),
            ),
            keyPhrases = listOf(
                Phrase("I'm here for sightseeing.", "観光で来ました。"),
                Phrase("I'm staying for one week.", "1週間滞在します。"),
                Phrase("I'm staying at the Hilton downtown.", "ダウンタウンのヒルトンに泊まります。"),
                Phrase("I work as an engineer.", "エンジニアとして働いています。"),
            ),
        ),
        Scenario(
            id = "hotel",
            category = Category.TRAVEL,
            emoji = "🏨",
            titleJa = "ホテルでチェックイン",
            titleEn = "Hotel Check-in",
            level = Level.INTERMEDIATE,
            descriptionJa = "チェックインの後、部屋のエアコンが壊れていることを伝えて対応をお願いします。",
            setting = "The front desk of a mid-size hotel in Sydney, late afternoon.",
            aiName = "Olivia",
            aiRole = "Olivia, a polite front desk clerk. The reservation exists. Breakfast is 6:30-10 on the 2nd floor. If the guest reports a problem with the room, apologize and offer to send maintenance or move them to another room.",
            userRole = "A guest checking in, who later notices the air conditioner in the room is broken.",
            userRoleJa = "宿泊客",
            opener = "Good afternoon, and welcome to the Harbor View Hotel. Are you checking in today?",
            missions = listOf(
                Mission("checkin", "予約名を伝えてチェックインする"),
                Mission("breakfast", "朝食の時間や場所を聞く"),
                Mission("problem", "部屋のエアコンの故障を伝え、対応を頼む"),
            ),
            keyPhrases = listOf(
                Phrase("I have a reservation under the name Tanaka.", "田中の名前で予約しています。"),
                Phrase("What time is breakfast served?", "朝食は何時からですか？"),
                Phrase("The air conditioner in my room isn't working.", "部屋のエアコンが動きません。"),
                Phrase("Would it be possible to change rooms?", "部屋を替えてもらうことはできますか？"),
            ),
        ),
        Scenario(
            id = "shopping",
            category = Category.DAILY,
            emoji = "🛍️",
            titleJa = "お店で返品・交換",
            titleEn = "Returning an Item",
            level = Level.INTERMEDIATE,
            descriptionJa = "買ったセーターのサイズが合わなかったので、交換か返金をお願いします。",
            setting = "The customer service counter of a clothing store in Toronto.",
            aiName = "Sam",
            aiRole = "Sam, a helpful store clerk. Returns need a receipt and are accepted within 30 days. A medium in the same color is out of stock, but it is available in navy, or the customer can get a full refund.",
            userRole = "A customer who bought a sweater that is too small.",
            userRoleJa = "お客さん",
            opener = "Hi, how can I help you today?",
            missions = listOf(
                Mission("reason", "返品・交換したい理由を説明する"),
                Mission("option", "別の色や返金など選択肢について相談する"),
                Mission("decide", "どうするか決めて伝える"),
            ),
            keyPhrases = listOf(
                Phrase("I'd like to exchange this sweater. It's too small.", "このセーターを交換したいです。小さすぎました。"),
                Phrase("Do you have it in a medium?", "Mサイズはありますか？"),
                Phrase("Here's my receipt.", "レシートはこちらです。"),
                Phrase("I think I'll just get a refund, then.", "それなら返金にしてもらいます。"),
            ),
        ),
        Scenario(
            id = "party",
            category = Category.SOCIAL,
            emoji = "🥂",
            titleJa = "パーティーで初対面の人と話す",
            titleEn = "Meeting Someone at a Party",
            level = Level.INTERMEDIATE,
            descriptionJa = "友人のホームパーティーで初めて会った人と自己紹介し、共通の話題を見つけよう。",
            setting = "A friend's casual house party in Los Angeles on a Saturday night.",
            aiName = "Chris",
            aiRole = "Chris, an outgoing graphic designer who loves hiking and trying new restaurants, and knows the host from college. Curious about Japan.",
            userRole = "A guest at the party who doesn't know many people.",
            userRoleJa = "パーティーの参加者",
            opener = "Hey! I don't think we've met yet. I'm Chris. How do you know Emily?",
            missions = listOf(
                Mission("intro", "自己紹介をする"),
                Mission("common", "趣味など共通の話題を見つける"),
                Mission("contact", "また会う約束や連絡先の交換を提案する"),
            ),
            keyPhrases = listOf(
                Phrase("Nice to meet you. I'm Ken.", "はじめまして、ケンです。"),
                Phrase("Emily and I work together.", "エミリーとは同僚なんです。"),
                Phrase("What do you do for fun?", "休みの日は何をしてるんですか？"),
                Phrase("We should hang out sometime!", "今度一緒に遊びましょう！"),
            ),
        ),
        Scenario(
            id = "weekend",
            category = Category.SOCIAL,
            emoji = "🎬",
            titleJa = "友達と週末の予定を立てる",
            titleEn = "Making Weekend Plans",
            level = Level.BEGINNER,
            descriptionJa = "友達と電話で、週末に何をするか・いつどこで会うかを決めます。",
            setting = "A phone call between two friends on a Thursday evening.",
            aiName = "Taylor",
            aiRole = "Taylor, a relaxed friend of the learner. Taylor is free on Saturday afternoon and Sunday, likes movies and food, and is open to suggestions.",
            userRole = "Taylor's friend who wants to hang out this weekend.",
            userRoleJa = "テイラーの友達",
            opener = "Hey! What's up? Are you doing anything this weekend?",
            missions = listOf(
                Mission("suggest", "やりたいことを提案する"),
                Mission("when", "日時を決める"),
                Mission("where", "待ち合わせ場所を決める"),
            ),
            keyPhrases = listOf(
                Phrase("Do you want to see a movie on Saturday?", "土曜日に映画を見に行かない？"),
                Phrase("How about meeting at two?", "2時に会うのはどう？"),
                Phrase("Let's meet in front of the station.", "駅の前で待ち合わせしよう。"),
                Phrase("Sounds good! See you then.", "いいね！じゃあそのときに。"),
            ),
        ),
        Scenario(
            id = "doctor",
            category = Category.TRAVEL,
            emoji = "🏥",
            titleJa = "病院で症状を説明する",
            titleEn = "Seeing a Doctor",
            level = Level.INTERMEDIATE,
            descriptionJa = "旅行中に体調を崩してクリニックへ。いつから・どんな症状かを伝えましょう。",
            setting = "A walk-in clinic in New York.",
            aiName = "Dr. Lee",
            aiRole = "Dr. Lee, a kind and patient doctor. Ask about symptoms, when they started, allergies, and current medication, then explain it looks like a common cold and recommend rest, fluids, and a mild medicine. This is a language-practice role-play, not real medical advice.",
            userRole = "A traveler who has had a sore throat and fever since yesterday.",
            userRoleJa = "患者（旅行者）",
            opener = "Hi, I'm Dr. Lee. So, what brings you in today?",
            missions = listOf(
                Mission("symptom", "症状を説明する"),
                Mission("since", "いつから症状があるか伝える"),
                Mission("question", "薬や注意点について質問する"),
            ),
            keyPhrases = listOf(
                Phrase("I have a sore throat and a fever.", "喉が痛くて熱があります。"),
                Phrase("It started yesterday morning.", "昨日の朝からです。"),
                Phrase("I'm allergic to penicillin.", "ペニシリンにアレルギーがあります。"),
                Phrase("How often should I take this medicine?", "この薬はどのくらいの頻度で飲めばいいですか？"),
            ),
        ),
        Scenario(
            id = "coworker",
            category = Category.WORK,
            emoji = "💬",
            titleJa = "同僚とスモールトーク",
            titleEn = "Small Talk with a Coworker",
            level = Level.INTERMEDIATE,
            descriptionJa = "月曜の朝、オフィスのキッチンで同僚と週末の話をします。会話を広げてみよう。",
            setting = "The office kitchen on a Monday morning at a tech company.",
            aiName = "Jordan",
            aiRole = "Jordan, a friendly coworker from the marketing team. Jordan went camping over the weekend and is a bit tired but in a good mood.",
            userRole = "A coworker from the engineering team.",
            userRoleJa = "同僚",
            opener = "Morning! Ugh, Mondays, right? How was your weekend?",
            missions = listOf(
                Mission("weekend", "自分の週末について話す"),
                Mission("follow", "相手の話に質問して会話を広げる"),
                Mission("close", "自然に会話を切り上げる"),
            ),
            keyPhrases = listOf(
                Phrase("It was pretty relaxing, actually.", "実はけっこうのんびりできたよ。"),
                Phrase("Oh nice, where did you go camping?", "いいね、どこにキャンプに行ったの？"),
                Phrase("That sounds like fun!", "楽しそう！"),
                Phrase("Anyway, I'd better get back to work. Talk later!", "さて、そろそろ仕事に戻らなきゃ。またあとで！"),
            ),
        ),
        Scenario(
            id = "meeting",
            category = Category.WORK,
            emoji = "📊",
            titleJa = "会議で意見を言う",
            titleEn = "Sharing Opinions in a Meeting",
            level = Level.ADVANCED,
            descriptionJa = "新機能のリリース時期を議論する会議。賛成・反対を理由付きで述べ、代案を出そう。",
            setting = "A video meeting at a software company discussing whether to release a new feature next week or delay it by a month.",
            aiName = "Morgan",
            aiRole = "Morgan, a product manager leading the meeting who wants to release next week. Morgan is open to other views but will push back politely and ask for reasons and data.",
            userRole = "An engineer on the team who has concerns about quality and testing.",
            userRoleJa = "チームのエンジニア",
            opener = "Okay, thanks for joining, everyone. So I'd really like to ship the new search feature next Monday. What do you think? Any concerns?",
            missions = listOf(
                Mission("opinion", "理由を添えて自分の意見を述べる"),
                Mission("disagree", "相手の意見に丁寧に反論する"),
                Mission("propose", "代案や妥協案を提案する"),
            ),
            keyPhrases = listOf(
                Phrase("I see your point, but I'm a bit concerned about testing.", "おっしゃることはわかりますが、テストが少し心配です。"),
                Phrase("From my perspective, we need at least another week.", "私の見解では、少なくともあと1週間は必要です。"),
                Phrase("What if we released it to a small group of users first?", "まず一部のユーザーに公開するのはどうでしょう？"),
                Phrase("Could we compromise on a beta release?", "ベータ版のリリースで折り合えませんか？"),
            ),
        ),
        Scenario(
            id = "interview",
            category = Category.WORK,
            emoji = "💼",
            titleJa = "英語の面接",
            titleEn = "Job Interview",
            level = Level.ADVANCED,
            descriptionJa = "外資系企業の面接。自己紹介・強み・志望動機を具体例を交えて話しましょう。",
            setting = "A video job interview for a position at an international company.",
            aiName = "Ms. Carter",
            aiRole = "Ms. Carter, a professional but friendly hiring manager. Ask common interview questions one at a time (tell me about yourself, strengths, a challenge you overcame, why this company) and ask natural follow-up questions.",
            userRole = "A job candidate applying for a position they are interested in.",
            userRoleJa = "応募者",
            opener = "Hi, thanks for taking the time to talk with us today. To start, could you tell me a little bit about yourself?",
            missions = listOf(
                Mission("self", "経歴を簡潔に自己紹介する"),
                Mission("strength", "具体例を交えて強みを話す"),
                Mission("why", "志望動機を伝える"),
            ),
            keyPhrases = listOf(
                Phrase("I've been working in sales for five years.", "5年間営業の仕事をしています。"),
                Phrase("One of my strengths is that I'm a quick learner.", "私の強みのひとつは、覚えが早いことです。"),
                Phrase("For example, in my last project, I ...", "例えば、前のプロジェクトでは…"),
                Phrase("I'm really drawn to your company's mission.", "御社のミッションにとても惹かれています。"),
            ),
        ),
    )

    private const val FREE_TALK_NAME = "Alex"
    private const val FREE_TALK_ROLE =
        "Alex, a friendly, curious conversation partner from Portland who works as a travel writer, loves food, music " +
            "and hearing about other cultures. Alex shares small bits about their own life too, so it feels like a real " +
            "two-way chat, not an interview."

    /** フリートーク (id は "free:<トピック>")。ミッションなしで Alex と自由に話す。 */
    val freeTalks: List<Scenario> = listOf(
        freeTalk(
            topic = "free",
            emoji = "💭",
            titleJa = "自由に話す",
            opener = "Hi! I'm Alex. It's great to chat with you. How's your day going so far?",
            focus = "Anything the learner wants to talk about. Follow their interests.",
        ),
        freeTalk(
            topic = "today",
            emoji = "📅",
            titleJa = "今日の出来事",
            opener = "Hey, it's Alex! So, tell me, what did you do today?",
            focus = "The learner's day: what they did, how they felt, anything interesting that happened.",
        ),
        freeTalk(
            topic = "hobbies",
            emoji = "🎸",
            titleJa = "趣味・好きなこと",
            opener = "Hi, I'm Alex! I'm curious, what do you like to do in your free time?",
            focus = "The learner's hobbies, favorite things, and why they like them.",
        ),
        freeTalk(
            topic = "travel",
            emoji = "✈️",
            titleJa = "旅行の思い出",
            opener = "Hi, I'm Alex! I love hearing travel stories. What's the best trip you've ever taken?",
            focus = "Travel memories and dream destinations.",
        ),
        freeTalk(
            topic = "work",
            emoji = "💻",
            titleJa = "仕事・勉強",
            opener = "Hi, I'm Alex! So, what do you do? Are you working or studying?",
            focus = "The learner's job or studies, what they enjoy and what is challenging.",
        ),
        freeTalk(
            topic = "future",
            emoji = "🌱",
            titleJa = "将来の目標",
            opener = "Hi, I'm Alex! Let's talk about goals. Is there something you really want to do in the next few years?",
            focus = "The learner's goals and dreams, including why they are learning English.",
        ),
    )

    private fun freeTalk(topic: String, emoji: String, titleJa: String, opener: String, focus: String) = Scenario(
        id = "free:$topic",
        category = Category.FREE,
        emoji = emoji,
        titleJa = titleJa,
        titleEn = "Free Talk",
        level = null,
        descriptionJa = "会話相手の Alex と「$titleJa」をテーマに自由に話しましょう。ミッションはありません。",
        setting = "A relaxed one-on-one video chat. Topic focus: $focus",
        aiName = FREE_TALK_NAME,
        aiRole = FREE_TALK_ROLE,
        userRole = "Themselves, a Japanese person practicing English conversation.",
        userRoleJa = "自分自身",
        opener = opener,
    )

    fun find(id: String): Scenario? = scenarios.firstOrNull { it.id == id } ?: freeTalks.firstOrNull { it.id == id }
}
